name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - "v*.*.*" # on every version tag will build a new android artifact.
jobs:
  build:
    name: Build App Bundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.2'
          channel: 'stable'
      - run: flutter --version
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.2'
        env:
          run: echo $JKS > ${{ secrets.STORE_FILE }} && echo -e "keyAlias=${{ secrets.KEY_ALIAS }}\nkeyPassword=${{ secrets.KEY_PASSWORD }}\nstoreFile=${{ secrets.STORE_FILE }}\nstorePassword=${{ secrets.STORE_PASSWORD }}" > android/key.properties
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle